services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-cityfix-app
    restart: unless-stopped
    working_dir: /var/www/cityfix
    volumes:
      - ./laravel-app:/var/www/cityfix
    environment:
      # Laravel specific environment variables
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_CHANNEL=stderr
      # Database configuration
      - DB_CONNECTION=mysql
      - DB_HOST=mysql_cityfix
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE:-cityfix}
      - DB_USERNAME=${MYSQL_USER:-cityfix_user}
      - DB_PASSWORD=${MYSQL_PASSWORD:-root}
    networks:
      - laravel
    depends_on:
      - db
  webserver:
    image: nginx:alpine
    container_name: nginx_cityfix
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel-app:/var/www/cityfix
      - ./nginx-production.conf:/etc/nginx/conf.d/default.conf # Configuración CON SSL
      - ./ssl:/etc/nginx/ssl # Volumen de certificados
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_cityfix
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-cityfix}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootcityfix}
      MYSQL_USER: ${MYSQL_USER:-cityfix_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
